import {
  UtensilsCrossed,
  CarTaxiFront,
  Package,
  Car,
  Laptop,
  Sparkles,
  Dumbbell,
  Shirt,
  Gem,
  CupSoda,
  Puzzle,
  Clapperboard,
  MapPin,
  Clock,
  Wallet,
  PiggyBank,
  ReceiptText,
  ArrowLeftRight,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  Food: UtensilsCrossed,
  Parcel: Package,
  Vehicle: Car,
  Computer: Laptop,
  "Beauty Products": Sparkles,
  Gym: Dumbbell,
  Clothes: Shirt,
  Accessories: Gem,
  Drinks: CupSoda,
  Toys: Puzzle,
  Entertainment: Clapperboard,
  Outing: MapPin,
  "Part Time": Clock,
  Salary: Wallet,
  Allowance: PiggyBank,
  Bills: ReceiptText,
  Transportation: CarTaxiFront,
  Transfer: ArrowLeftRight,
};
